export const commonMedicines = [
  { name: "Paracetamol", type: "tablet" },
  { name: "Ibuprofen", type: "tablet" },
  { name: "Amoxicillin", type: "capsule" },
  { name: "Vitamin C", type: "capsule" },
  { name: "Cough Syrup", type: "syrup" },
  { name: "Ranitidine", type: "tablet" },
  { name: "Metformin", type: "tablet" },
  { name: "Insulin", type: "injection" },
  { name: "Salbutamol", type: "ml" },
  { name: "Diclofenac", type: "tablet" },
  { name: "Cetirizine", type: "tablet" },
  { name: "Azithromycin", type: "capsule" },
  { name: "Omeprazole", type: "capsule" },
  { name: "Multivitamin Syrup", type: "syrup" },
  { name: "Heparin", type: "injection" },
  { name: "Loratadine", type: "tablet" },
  { name: "Levofloxacin", type: "tablet" },
  { name: "Pantoprazole", type: "tablet" },
  { name: "Doxycycline", type: "capsule" },
  { name: "Vitamin D3", type: "capsule" },
  { name: "Amoxicillin Syrup", type: "syrup" },
  { name: "Morphine", type: "injection" },
  { name: "Magnesium Hydroxide", type: "ml" },
  { name: "Folic Acid", type: "tablet" },
  { name: "Prednisolone", type: "tablet" },
  { name: "Levothyroxine", type: "tablet" },
  { name: "Cefixime", type: "capsule" },
  { name: "Metronidazole", type: "tablet" },
  { name: "Azithromycin Syrup", type: "syrup" },
  { name: "Hydrocortisone Injection", type: "injection" },
  { name: "Aspirin", type: "tablet" },
  { name: "Clarithromycin", type: "capsule" },
  { name: "Omeprazole Suspension", type: "ml" },
  { name: "Vitamin B12", type: "injection" },
  { name: "Azathioprine", type: "tablet" },
  { name: "Ceftriaxone", type: "injection" },
  { name: "Diclofenac Gel", type: "ml" },
  { name: "Riboflavin", type: "tablet" },
  { name: "Omeprazole Capsule", type: "capsule" },
  { name: "Paracetamol Syrup", type: "syrup" },
  { name: "Clindamycin", type: "capsule" },
  { name: "Insulin Glargine", type: "injection" },
  { name: "Metoclopramide", type: "ml" },
  { name: "Cefadroxil", type: "capsule" },
  { name: "Pantoprazole Syrup", type: "syrup" },
];

export const medicineTypes: { label: string; value: MedicineType }[] = [
  { label: "Tablet", value: "tablet" },
  { label: "ml (liquid)", value: "ml" },
  { label: "Syrup", value: "syrup" },
  { label: "Injection", value: "injection" },
  { label: "Cream", value: "cream" },
];
